app:
  # Number of repeated sequences to search for
  repeatedSequences: 4
  mutationsRequired: 2
  saveResults: true

db:
  type: 'mysql'
  port: 3306
  host: 'your-host'
  database: 'your-database'
  synchronize: true

